###
### Workflow that test code in pull requests
###

name: Test

# Note: No name so it uses the name associated with the pull request merge to main

on:
  pull_request:
    paths:
    - 'epic-comments/**'

jobs:
  test-epic-comments:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Python Version
        run: echo "PYTHON_VERSION=$(cat .python-version | grep ^[^#])" >> $GITHUB_ENV

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pipenv"

      - name: Install pipenv
        run: pip install --user pipenv

      - name: Install Python dependencies
        working-directory: ./epic-comments
        run: make setup-dev

      - name: Test epic-comments
        working-directory: ./epic-comments
        run: make test
